<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Tests\Unit\Laravel\ValidationExceptionTest" file="E:\CodifyTech\Innochannel\sdk\implementations\php\tests\Unit\Laravel\ValidationExceptionTest.php" tests="5" assertions="16" errors="0" failures="0" skipped="0" time="0.005103">
    <testcase name="test_validation_exception_returns_422_with_errors" file="E:\CodifyTech\Innochannel\sdk\implementations\php\tests\Unit\Laravel\ValidationExceptionTest.php" line="20" class="Tests\Unit\Laravel\ValidationExceptionTest" classname="Tests.Unit.Laravel.ValidationExceptionTest" assertions="4" time="0.003828"/>
    <testcase name="test_validation_exception_includes_formatted_errors" file="E:\CodifyTech\Innochannel\sdk\implementations\php\tests\Unit\Laravel\ValidationExceptionTest.php" line="42" class="Tests\Unit\Laravel\ValidationExceptionTest" classname="Tests.Unit.Laravel.ValidationExceptionTest" assertions="2" time="0.000329"/>
    <testcase name="test_validation_exception_includes_context_when_available" file="E:\CodifyTech\Innochannel\sdk\implementations\php\tests\Unit\Laravel\ValidationExceptionTest.php" line="64" class="Tests\Unit\Laravel\ValidationExceptionTest" classname="Tests.Unit.Laravel.ValidationExceptionTest" assertions="2" time="0.000106"/>
    <testcase name="test_nested_field_errors_are_handled_correctly" file="E:\CodifyTech\Innochannel\sdk\implementations\php\tests\Unit\Laravel\ValidationExceptionTest.php" line="82" class="Tests\Unit\Laravel\ValidationExceptionTest" classname="Tests.Unit.Laravel.ValidationExceptionTest" assertions="4" time="0.000345"/>
    <testcase name="test_empty_errors_array_is_handled" file="E:\CodifyTech\Innochannel\sdk\implementations\php\tests\Unit\Laravel\ValidationExceptionTest.php" line="107" class="Tests\Unit\Laravel\ValidationExceptionTest" classname="Tests.Unit.Laravel.ValidationExceptionTest" assertions="4" time="0.000494"/>
  </testsuite>
</testsuites>
